### PR TITLE
Basic test working etc.

### PR DESCRIPTION
**Pull request by zmoon**
Note simple case of dict of key-value pairs (with values being non-array) was close to working before this. Now it is, with the rest of test YAML commented out for now.

Also:
* add CI
* add initial pre-commit config
* a few docs tweaks

### CODE REVIEW

**Review by bbakernoaa — APPROVED** [review]

**Comment by bbakernoaa** [comment]
@zmoon Ford failed in the CI.  Looks like we need to install it in the CI. 

also we took out the sequence test.  We need that to work for the future pieces.

**Comment by zmoon** [comment]
I think I fixed the issue with the `ford`. The tests involving sequences I was getting some issues, can address in another PR.

**Comment by bbakernoaa** [comment]
Almost. Problems in the deployment. Not sure if this is due to the PR through or if it will be pushed through when the PR is complete.

**Comment by zmoon** [comment]
Yeah I think it's just that my fork doesn't have permission to deploy to your gh-pages branch. I attempted to change it so it only deploys from upstream main branch.

**Pull request merged**
